# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e081670850dff3bf4bfdfed20dd5c750"
name = "My First CLI App"
handle = "cli-basics"
application_url = "https://homeland-tunisia-flooring-experiencing.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-6fcb2336.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://homeland-tunisia-flooring-experiencing.trycloudflare.com/auth/callback",
  "https://homeland-tunisia-flooring-experiencing.trycloudflare.com/auth/shopify/callback",
  "https://homeland-tunisia-flooring-experiencing.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
