name: Deploy app
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: List directory contents
        run: ls -la ./cli-basics
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 22
          cache: 'npm'
      - name: Install npm dependencies
        run: npm install
        working-directory: ./cli-basics
      - name: Install Shopify CLI
        run: npm install -g @shopify/cli@latest
        working-directory: ./cli-basics
      - name: Deploy
        env:
          # Token from the Partner Dashboard
          SHOPIFY_CLI_PARTNERS_TOKEN: ${{ secrets.SHOPIFY_CLI_PARTNERS_TOKEN }}
          COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
          # .env content after a deploy
          SHOPIFY_API_KEY: ${{ vars.SHOPIFY_API_KEY }}
        run: shopify app deploy -f --source-control-url "$COMMIT_URL"
        working-directory: ./cli-basics
